services:
  backend:
    build:
      context: ./tenderhack_samara_2025/AEProject
      dockerfile: Dockerfile
    container_name: tenderhack-backend
    ports:
      - "8000:8000"
    environment:
      - UVICORN_PORT=8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./tenderhack_samara_2025/AEProject:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: tenderhack-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
